# Generated by Django 5.2 on 2025-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproj', '0003_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_logically_delete', 'Can logically delete product'), ('can_undelete', 'Can restore deleted product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
