# Generated by Django 5.2 on 2025-05-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproj', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_logically_delete', 'Can logically delete product'), ('can_undelete', 'Can restore deleted product'), ('delete_product_physical', 'Can physically delete product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
